//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSelection.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseSelectionDBEntities : DbContext
    {
        public HouseSelectionDBEntities()
            : base("name=HouseSelectionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectGroup> ProjectGroup { get; set; }
        public virtual DbSet<RoomType> RoomType { get; set; }
        public virtual DbSet<ShakingNumberResult> ShakingNumberResult { get; set; }
        public virtual DbSet<Subscriber> Subscriber { get; set; }
        public virtual DbSet<SubscriberFamilyMember> SubscriberFamilyMember { get; set; }
        public virtual DbSet<SubscriberProjectMapping> SubscriberProjectMapping { get; set; }
        public virtual DbSet<BackEndAccount> BackEndAccount { get; set; }
        public virtual DbSet<ApplicationAccount> ApplicationAccount { get; set; }
        public virtual DbSet<BackEndAccountLoginRecord> BackEndAccountLoginRecord { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<HouseGroup> HouseGroup { get; set; }
    }
}
