//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSelection.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseSelectionRecord
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int HouseID { get; set; }
        public int SubscriberID { get; set; }
        public System.DateTime SelectTime { get; set; }
        public string SelectImageUrl1 { get; set; }
        public string SelectImageUrl2 { get; set; }
        public string SelectImageUrl3 { get; set; }
        public bool IsAbandon { get; set; }
        public Nullable<System.DateTime> AbandonTime { get; set; }
        public string AbandonImageUrl1 { get; set; }
        public string AbandonImageUrl2 { get; set; }
        public string AbandonImageUrl3 { get; set; }
    
        public virtual House House { get; set; }
        public virtual Project Project { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
