//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSelection.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberFamilyMember
    {
        public int ID { get; set; }
        public int SubscriberID { get; set; }
        public string Name { get; set; }
        public string IdentityNumber { get; set; }
        public string Relationship { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
    }
}
