//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSelection.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscriber()
        {
            this.SubscriberProjectMapping = new HashSet<SubscriberProjectMapping>();
            this.House = new HashSet<House>();
            this.SubscriberFamilyMember = new HashSet<SubscriberFamilyMember>();
            this.HouseSelectionRecord = new HashSet<HouseSelectionRecord>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string IdentityNumber { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string MaritalStatus { get; set; }
        public string ResidenceArea { get; set; }
        public string WorkArea { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriberProjectMapping> SubscriberProjectMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<House> House { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriberFamilyMember> SubscriberFamilyMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseSelectionRecord> HouseSelectionRecord { get; set; }
    }
}
