//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSelection.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelephoneNoticeRecord
    {
        public int ID { get; set; }
        public int ShakingNumberResultID { get; set; }
        public Nullable<System.DateTime> NoticeTime { get; set; }
        public int ResultType { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public int FrontEndAccountID { get; set; }
        public string NoticeTelephone { get; set; }
    
        public virtual ShakingNumberResult ShakingNumberResult { get; set; }
        public virtual FrontEndAccount FrontEndAccount { get; set; }
    }
}
